stages:
  - build

build_app:
  stage: build
  dependencies: []
  tags:
  - stand-shell
  script:
  - docker run -i --rm --name my-maven-project -v "$(pwd)":/mymaven -w /mymaven maven:3.3-jdk-8 mvn clean install
