stages:
  - build

build_app:
  stage: build
  dependencies: []
  tags:
  - stand-shell
  script:
  - docker run -it --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn clean install
